apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-app
  name: nginx-app
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - image: 664341837355.dkr.ecr.us-west-1.amazonaws.com/spoyer/nginx-plus-ubuntu20.04:latest
        imagePullPolicy: Always
        name: nginx-app
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-confd-cm-vol
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-confd-cm-vol
        configMap:
          name: nginx-conf
          items:
          - key: server-conf
            path: api.conf
