apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  labels:
    run: nginx-apigw
  name: nginx-apigw
  namespace: nginx
spec:
  containers:
  - image: 664341837355.dkr.ecr.us-west-1.amazonaws.com/spoyer/nginx-plus-ubuntu20.04:latest
    imagePullPolicy: Always
    name: nginx-apigw
    ports:
    - containerPort: 80
    - containerPort: 9000
    volumeMounts:
    - name: nginx-confd-cm-vol
      mountPath: /etc/nginx/conf.d
    - name: nginx-streamd-cm-vol
      mountPath: /etc/nginx/stream.conf.d
  volumes:
  - name: nginx-confd-cm-vol
    configMap:
      name: nginx-confd
      items: 
      - key: apigw-conf
        path: apigw.conf
  - name: nginx-streamd-cm-vol
    configMap:
      name: nginx-streamd
      items: 
      - key: stream-conf
        path: stream-zone-sync.conf
