apiVersion: v1
data:
  apigw-conf: |
    limit_req_zone $http_auth zone=req1:1M rate=2r/s sync;
    limit_req_zone $jwt_claim_uid zone=req2:1M rate=2r/s sync;

    upstream api-app {
            zone api-apps 1m;
            resolver 10.100.0.10;
            server api-svc.app.svc.cluster.local resolve;
    }

    server {
        listen       80 default_server;
        server_name  localhost;

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            return   503 "503\n";
        }

        location /v1/jwt {
            limit_req zone=req2;
            limit_req_log_level info;
            proxy_pass http://api-svc.app.svc.cluster.local;
        }

        location /v1/auth {
            limit_req zone=req1;
            limit_req_log_level info;
            proxy_pass http://api-svc.app.svc.cluster.local;
        }
    }
kind: ConfigMap
metadata:
  name: nginx-confd
  namespace: nginx
